//
// Generated file, do not edit! Created by opp_msgc 4.2 from applicationlayer/EtherCatFrame.msg.
//

#ifndef _ETHERCATFRAME_M_H_
#define _ETHERCATFRAME_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applicationlayer/EtherCatFrame.msg</tt> by opp_msgc.
 * <pre>
 * packet EtherCatFrame {
 *     
 *     
 *     
 *     
 *     int data;
 *    
 * }
 * </pre>
 */
class EtherCatFrame : public ::cPacket
{
  protected:
    int data_var;

  private:
    void copy(const EtherCatFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EtherCatFrame&);

  public:
    EtherCatFrame(const char *name=NULL, int kind=0);
    EtherCatFrame(const EtherCatFrame& other);
    virtual ~EtherCatFrame();
    EtherCatFrame& operator=(const EtherCatFrame& other);
    virtual EtherCatFrame *dup() const {return new EtherCatFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getData() const;
    virtual void setData(int data);
};

inline void doPacking(cCommBuffer *b, EtherCatFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, EtherCatFrame& obj) {obj.parsimUnpack(b);}


#endif // _ETHERCATFRAME_M_H_
