//
// Generated file, do not edit! Created by opp_msgc 4.2 from datalinklayer/split8.msg.
//

#ifndef _SPLIT8_M_H_
#define _SPLIT8_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>datalinklayer/split8.msg</tt> by opp_msgc.
 * <pre>
 * packet split8{
 * 
 * char vector[8];
 * 
 * }
 * </pre>
 */
class split8 : public ::cPacket
{
  protected:
    char vector_var[8];

  private:
    void copy(const split8& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const split8&);

  public:
    split8(const char *name=NULL, int kind=0);
    split8(const split8& other);
    virtual ~split8();
    split8& operator=(const split8& other);
    virtual split8 *dup() const {return new split8(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getVectorArraySize() const;
    virtual char getVector(unsigned int k) const;
    virtual void setVector(unsigned int k, char vector);
};

inline void doPacking(cCommBuffer *b, split8& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, split8& obj) {obj.parsimUnpack(b);}


#endif // _SPLIT8_M_H_
